---
# For detailed instructions on using this file, visit:
# https://aka.ms/alz/accelerator/docs

# Basic Inputs
iac_type: "terraform"
bootstrap_module_name: "alz_local"
starter_module_name: "platform_landing_zone"

# Shared Interface Inputs
bootstrap_location: "westeurope"
starter_locations: ["westeurope", "northeurope"]
root_parent_management_group_id: ""
subscription_id_management: "f45a9cdc-bf42-4cec-8394-19cf4b3dbbca"
subscription_id_identity: "f45a9cdc-bf42-4cec-8394-19cf4b3dbbca"
subscription_id_connectivity: "f45a9cdc-bf42-4cec-8394-19cf4b3dbbca"

# Bootstrap Inputs
target_directory: ""
create_bootstrap_resources_in_azure: true
bootstrap_subscription_id: "f45a9cdc-bf42-4cec-8394-19cf4b3dbbca"
service_name: "alz"
environment_name: "mgmt"
postfix_number: 1
grant_permissions_to_current_user: true

# Advanced Inputs
bootstrap_module_version: "latest"
starter_module_version: "latest"
#output_folder_path: "/accelerator/output"
